# Generated by Django 4.0.1 on 2022-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dp',
            name='Backlog',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='Blocked',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='Closed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='CodeReview',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='InProgress',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='NeedsTriage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='Open',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='ReadyforProduction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='ReadyforTesting',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dp',
            name='ToDo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
