# Generated by Django 4.0.1 on 2022-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0004_dpm_dpmexternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dp',
            name='LastUpdate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='dpexternal',
            name='LastUpdate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='dpm',
            name='LastUpdate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='dpmexternal',
            name='LastUpdate',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
