# Generated by Django 4.0.1 on 2022-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0007_impactareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDACurrentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDAType', models.CharField(blank=True, max_length=30)),
                ('Number', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EDAPreviousMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDAType', models.CharField(blank=True, max_length=30)),
                ('Number', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application', models.CharField(blank=True, max_length=30)),
                ('Number', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
