# Generated by Django 4.0.1 on 2022-08-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0009_edalearnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFDtotalJiras', models.CharField(blank=True, max_length=150)),
                ('CFDtotalFixed', models.CharField(blank=True, max_length=150)),
                ('CFDtotalMRT', models.CharField(blank=True, max_length=150)),
                ('CFDtotalNotClosed', models.CharField(blank=True, max_length=150)),
                ('CFDtotalCurrentFix', models.CharField(blank=True, max_length=150)),
                ('CFDtotalNoise', models.CharField(blank=True, max_length=150)),
                ('CFDtalkJiras', models.CharField(blank=True, max_length=150)),
                ('CFDtalkFixed', models.CharField(blank=True, max_length=150)),
                ('CFDtalkMRT', models.CharField(blank=True, max_length=150)),
                ('CFDtalkNotClosed', models.CharField(blank=True, max_length=150)),
                ('CFDtalkCurrentFix', models.CharField(blank=True, max_length=150)),
                ('CFDCCJiras', models.CharField(blank=True, max_length=150)),
                ('CFDCCFixed', models.CharField(blank=True, max_length=150)),
                ('CFDCCMRT', models.CharField(blank=True, max_length=150)),
                ('CFDCCNotClosed', models.CharField(blank=True, max_length=150)),
                ('CFDCCCurrentFix', models.CharField(blank=True, max_length=150)),
                ('CFDCCNoise', models.CharField(blank=True, max_length=150)),
                ('CFDINTJiras', models.CharField(blank=True, max_length=150)),
                ('CFDINTFixed', models.CharField(blank=True, max_length=150)),
                ('CFDINTMRT', models.CharField(blank=True, max_length=150)),
                ('CFDINTNotClosed', models.CharField(blank=True, max_length=150)),
                ('CFDINTCurrentFix', models.CharField(blank=True, max_length=150)),
                ('CFDINTNoise', models.CharField(blank=True, max_length=150)),
                ('CFDLastUpdate', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
