# Generated by Django 4.0.1 on 2022-08-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0010_cfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfd',
            name='CFDtalkNoise',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
