# Generated by Django 4.0.1 on 2022-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0011_cfd_cfdtalknoise'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFDtotalJiras', models.CharField(blank=True, max_length=150)),
                ('IFDtotalFixed', models.CharField(blank=True, max_length=150)),
                ('IFDtotalMRT', models.CharField(blank=True, max_length=150)),
                ('IFDtotalNotClosed', models.CharField(blank=True, max_length=150)),
                ('IFDtotalCurrentFix', models.CharField(blank=True, max_length=150)),
                ('IFDtotalNoise', models.CharField(blank=True, max_length=150)),
                ('IFDtalkJiras', models.CharField(blank=True, max_length=150)),
                ('IFDtalkFixed', models.CharField(blank=True, max_length=150)),
                ('IFDtalkMRT', models.CharField(blank=True, max_length=150)),
                ('IFDtalkNotClosed', models.CharField(blank=True, max_length=150)),
                ('IFDtalkCurrentFix', models.CharField(blank=True, max_length=150)),
                ('IFDtalkNoise', models.CharField(blank=True, max_length=150)),
                ('IFDCCJiras', models.CharField(blank=True, max_length=150)),
                ('IFDCCFixed', models.CharField(blank=True, max_length=150)),
                ('IFDCCMRT', models.CharField(blank=True, max_length=150)),
                ('IFDCCNotClosed', models.CharField(blank=True, max_length=150)),
                ('IFDCCCurrentFix', models.CharField(blank=True, max_length=150)),
                ('IFDCCNoise', models.CharField(blank=True, max_length=150)),
                ('IFDINTJiras', models.CharField(blank=True, max_length=150)),
                ('IFDINTFixed', models.CharField(blank=True, max_length=150)),
                ('IFDINTMRT', models.CharField(blank=True, max_length=150)),
                ('IFDINTNotClosed', models.CharField(blank=True, max_length=150)),
                ('IFDINTCurrentFix', models.CharField(blank=True, max_length=150)),
                ('IFDINTNoise', models.CharField(blank=True, max_length=150)),
                ('IFDLastUpdate', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
