# Generated by Django 4.0.1 on 2022-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0012_ifd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfd',
            name='CFDCCPriorityH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDCCPriorityL',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDCCPriorityM',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDCCPriorityU',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDINTPriorityH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDINTPriorityL',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDINTPriorityM',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDINTPriorityU',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtalkPriorityH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtalkPriorityL',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtalkPriorityM',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtalkPriorityU',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtotalPriorityH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtotalPriorityL',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtotalPriorityM',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CFDtotalPriorityU',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
