# Generated by Django 4.0.1 on 2022-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityboard', '0014_cfddpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDMOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOBCFDtotalJiras', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalFixed', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalMRT', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalNotClosed', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalCurrentFix', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalNoise', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalPriorityH', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalPriorityM', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalPriorityL', models.CharField(blank=True, max_length=150)),
                ('MOBCFDtotalPriorityU', models.CharField(blank=True, max_length=150)),
                ('MOBCFDLastUpdate', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
